-- Durable admin alerts for automated T2Hub session refresh failures.
create table if not exists public.t2hub_refresh_alerts (
  id uuid primary key default gen_random_uuid(),
  account_id uuid not null references public.t2hub_accounts(id) on delete cascade,
  severity text not null default 'error' check (severity in ('warning', 'error')),
  message text not null,
  occurred_at timestamptz not null default now(),
  acknowledged_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists t2hub_refresh_alerts_open_idx
  on public.t2hub_refresh_alerts (acknowledged_at, occurred_at desc);

alter table public.t2hub_refresh_alerts enable row level security;
revoke all on table public.t2hub_refresh_alerts from anon, authenticated;

comment on table public.t2hub_refresh_alerts is
  'Admin-visible alerts generated by automated encrypted T2Hub session refresh failures.';
