import AsyncStorage from "@react-native-async-storage/async-storage";
import { StatusBar } from "expo-status-bar";
import React, { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";

const API_BASE = "https://xklwzkraobxetxdcysun.supabase.co/functions/v1";
type EventRow = { id: string; accountName: string; operation: string; outcome: "success" | "failure"; reservationId?: string | null; createdAt?: string };
type Dashboard = { stats: { totalAccounts: number; lifetimeBookingSuccesses?: number; lifetimeBookingFailures?: number }; live: { sessionAccounts: number; syncedAccounts: number; syncFailures: number; reauthRequired?: number; expiredRefreshSessions?: number; refreshedAt?: string }; bookingEvents: EventRow[] };

async function api(path: string, options: RequestInit = {}) {
  const token = await AsyncStorage.getItem("access_token");
  const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.message || "Request failed");
  return data;
}

export default function App() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [refreshing, setRefreshing] = useState(false);
  const load = async () => { setError(""); try { setDashboard(await api("/access-admin/dashboard")); } catch (e) { setError((e as Error).message); await AsyncStorage.removeItem("access_token"); setDashboard(null); } };
  useEffect(() => { AsyncStorage.getItem("access_token").then((token) => { if (token) void load(); }); }, []);
  const signIn = async () => { setLoading(true); setError(""); try { const result = await api("/access-auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); await AsyncStorage.setItem("access_token", result.accessToken); await load(); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } };
  const eventRows = useMemo(() => dashboard?.bookingEvents?.slice(0, 12) || [], [dashboard]);
  if (!dashboard) return <SafeAreaView style={styles.auth}><StatusBar style="light" /><View style={styles.authCard}><Text style={styles.eyebrow}>SVP BOOKING · BANGLADESH</Text><Text style={styles.title}>Operations, clearly.</Text><Text style={styles.muted}>Secure mobile access to live bookings, session health and the lifetime portal ledger.</Text><TextInput style={styles.input} placeholder="Admin email" placeholderTextColor="#8190ad" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail} /><TextInput style={styles.input} placeholder="Password" placeholderTextColor="#8190ad" secureTextEntry value={password} onChangeText={setPassword} /><Pressable style={styles.button} onPress={signIn} disabled={loading}><Text style={styles.buttonText}>{loading ? "Signing in…" : "Sign in"}</Text></Pressable>{error ? <Text style={styles.error}>{error}</Text> : null}</View></SafeAreaView>;
  return <SafeAreaView style={styles.screen}><StatusBar style="dark" /><ScrollView contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={async () => { setRefreshing(true); await load(); setRefreshing(false); }} />}><View style={styles.header}><View><Text style={styles.eyebrowDark}>LIVE OPERATIONS</Text><Text style={styles.heading}>Control centre</Text></View><Pressable onPress={async () => { await AsyncStorage.removeItem("access_token"); setDashboard(null); }}><Text style={styles.logout}>Sign out</Text></Pressable></View><View style={styles.hero}><Text style={styles.heroLabel}>SVP BOOKING BANGLADESH</Text><Text style={styles.heroTitle}>Booking system health</Text><Text style={styles.heroText}>Authoritative data from the protected admin API.</Text></View><View style={styles.grid}><Metric label="Accounts" value={dashboard.stats.totalAccounts} /><Metric label="Lifetime success" value={dashboard.stats.lifetimeBookingSuccesses || 0} positive /><Metric label="Lifetime failed" value={dashboard.stats.lifetimeBookingFailures || 0} danger /><Metric label="Re-auth needed" value={dashboard.live.reauthRequired || 0} danger={!!dashboard.live.reauthRequired} /></View><View style={styles.panel}><Text style={styles.panelTitle}>Session health</Text><Text style={styles.panelValue}>{dashboard.live.syncFailures ? `${dashboard.live.syncFailures} sessions need attention` : "Healthy"}</Text><Text style={styles.muted}>{dashboard.live.expiredRefreshSessions || 0} expired refresh tokens · {dashboard.live.syncedAccounts} accounts synced</Text></View><View style={styles.panel}><Text style={styles.panelTitle}>Lifetime booking ledger</Text>{eventRows.length ? eventRows.map((event) => <View style={styles.row} key={event.id}><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{event.accountName}</Text><Text style={styles.muted}>{event.operation}{event.reservationId ? ` · #${event.reservationId}` : ""}</Text></View><Text style={event.outcome === "success" ? styles.success : styles.failure}>{event.outcome.toUpperCase()}</Text></View>) : <Text style={styles.muted}>No portal events recorded yet.</Text>}</View></ScrollView></SafeAreaView>;
}
function Metric({ label, value, positive, danger }: { label: string; value: number; positive?: boolean; danger?: boolean }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, positive && styles.success, danger && styles.failure]}>{value}</Text></View>; }
const styles = StyleSheet.create({ auth: { flex: 1, backgroundColor: "#0a1628", justifyContent: "center", padding: 24 }, authCard: { gap: 16 }, eyebrow: { color: "#60a5fa", fontWeight: "800", letterSpacing: 2, fontSize: 12 }, title: { color: "#f5f8ff", fontSize: 38, fontWeight: "800" }, muted: { color: "#8190ad", fontSize: 13, lineHeight: 20 }, input: { backgroundColor: "#142442", color: "#f5f8ff", borderRadius: 12, padding: 15, fontSize: 15 }, button: { backgroundColor: "#60a5fa", borderRadius: 12, padding: 16, alignItems: "center" }, buttonText: { color: "#071325", fontWeight: "800", fontSize: 15 }, error: { color: "#fda4af", fontSize: 13 }, screen: { flex: 1, backgroundColor: "#f4f7fb" }, content: { padding: 20, gap: 16 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, eyebrowDark: { color: "#4361a8", fontWeight: "800", letterSpacing: 1.5, fontSize: 11 }, heading: { color: "#16213d", fontSize: 30, fontWeight: "800" }, logout: { color: "#4361a8", fontWeight: "700" }, hero: { backgroundColor: "#142b56", borderRadius: 20, padding: 22, gap: 8 }, heroLabel: { color: "#8fc4ff", fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, heroTitle: { color: "#fff", fontSize: 24, fontWeight: "800" }, heroText: { color: "#b9cae7", fontSize: 13 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, metric: { width: "48%", backgroundColor: "#fff", borderRadius: 15, padding: 16, gap: 8 }, metricLabel: { color: "#77829c", fontSize: 11, fontWeight: "700" }, metricValue: { color: "#16213d", fontSize: 28, fontWeight: "800" }, panel: { backgroundColor: "#fff", borderRadius: 15, padding: 18, gap: 7 }, panelTitle: { color: "#16213d", fontSize: 17, fontWeight: "800" }, panelValue: { color: "#4361a8", fontSize: 16, fontWeight: "700" }, row: { flexDirection: "row", alignItems: "center", paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#edf0f5" }, rowTitle: { color: "#243152", fontWeight: "700", fontSize: 13 }, success: { color: "#07875b", fontWeight: "800" }, failure: { color: "#c23b4a", fontWeight: "800" }
});
